spring:
  application:
    name: ${APP_NAME:ms-unir-store-buscador}

server:
    port: 8005
    error:
      include-stacktrace: on_param

eureka:
     client:
       registerWithEureka: true
       fetchRegistry: true
       service-url:
         defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
     instance:
       preferIpAddress: false # TRUE para uso local, false para trabajar con hostname
       hostname: ${HOSTNAME:ms-unir-store-buscador}
       non-secure-port-enabled: false
       secure-port-enabled: true
       non-secure-port: 80
       secure-port: 443
##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE