spring:
  application:
    name: store-core
  datasource:
    url: jdbc:mariadb://localhost:3306/unir_store
    username: root
    password: root
  flyway:
    url: jdbc:mariadb://localhost:3306/unir_store
    user: root
    password: root
    enabled: true
    schemas: unir_store
    locations: classpath:db/migration/mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  server:
  port: 8003
  error:
    include-stacktrace: on_param
  eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false # TRUE para uso local, false para trabajar con hostname
    hostname: ms-unir-store1
  ## Configuracion secundaria (custom)
getProduct:
  url: http://ms-unir-store/products/%s